#!/usr/bin/python3

import csv, getopt, os, re, sys, unicodedata

def main(argv):
    inputfile = ''
    outputfile = ''
    try:
       opts, args = getopt.getopt(argv,"hi:o:",["ifile=","ofile="])
    except getopt.GetoptError:
       print('gaelcc -i <inputfile> -o <outputfile>')
       sys.exit(2)
    for opt, arg in opts:
       if opt == '-h':
          print('gaelcc -i <inputfile> -o <outputfile>')
          sys.exit()
       elif opt in ("-i", "--ifile"):
          inputfile = arg
       elif opt in ("-o", "--ofile"):
          outputfile = arg

    # Input .gc script:
    with open(inputfile, 'r') as inputfile:
        script = inputfile.read()

    # Dictionary file:
    with open('foclóir.csv', 'r') as f:
         ga_to_en = dict(filter(None, csv.reader(f)))
    del ga_to_en['Gaeilge']  # delete header

    # For every Irish term, translate to English (original C), except when
    # the word is contained within quotes:
    def replace(m):
        matches.append(m.group())
        return ga_to_en[i]

    for i in ga_to_en:
        matches = []
        regex = '(?<!")' + i + '(?!")'
        script = re.sub(regex, replace, script)

    # Write translated version to a file:
    f = open('translated-input.c', 'w')
    f.write(script)
    f.close()

    # Compile and remove the intermediary translated file:
    os.system('gcc translated-input.c -o ' + outputfile)
    os.system('rm -f translated-input.c')

if __name__ == "__main__":
    main(sys.argv[1:])
